<?php

$config_mysqli_host = "127.0.0.1";
$config_mysqli_user = "root";
$config_mysqli_mdp = "";
$config_mysqli_db = "Major_panel";

//$config_mysqli_table_session = "base_session";
//$config_mysqli_table_user = "base_user";
$config_mysqli_table_module = "module";

//$config_account_expire = "1296000"; //15 jours

//$config_hash_seed = "28214-73956-32084-45903-72186-03520";

$config_jobs_domainefile = "/home/u259806663/public_html/MajorPanel/cron.php";

?>